"""
test_e2e.py — End-to-end evaluation of the full multi-agent pipeline.

Runs the full Supervisor→Planner→Researcher→Critic pipeline on a subset of the
golden dataset and evaluates outputs with two metrics:

  1. AnswerRelevancyMetric  — does the output answer the question?
  2. GEval "Correctness"    — do the facts match the expected_output reference?

Golden dataset subsets tested:
  - happy_path examples only (3 cases, deterministic and in-domain)
  - Optionally the full dataset via pytest mark (deepeval test run tests/test_e2e.py -k full)

save_report interrupts are auto-approved so the test does not require human input.

Run with debug output:
  deepeval test run tests/test_e2e.py --debug
  DEBUG=1 deepeval test run tests/test_e2e.py
"""

from __future__ import annotations

import json
import os
import sys
from pathlib import Path
from uuid import uuid4

sys.path.insert(0, str(Path(__file__).parent.parent))

import pytest
import deepeval
from deepeval.metrics import AnswerRelevancyMetric, GEval
from deepeval.test_case import LLMTestCase, LLMTestCaseParams
from langchain_core.messages import AIMessage
from langgraph.types import Command

from config import settings
from tools import debug_print
from supervisor import supervisor, reset_supervisor_limits, set_active_thread_id, clear_active_thread_id

EVAL_MODEL = os.getenv("DEEPEVAL_MODEL", settings.eval_model)
DATASET_PATH = Path(__file__).parent / "golden_dataset.json"

# ── Metrics ───────────────────────────────────────────────────────────────────

answer_relevancy = AnswerRelevancyMetric(threshold=0.65, model=EVAL_MODEL)

correctness = GEval(
    name="Correctness",
    evaluation_steps=[
        "IMPORTANT CONTEXT: 'actual output' is a FULL RESEARCH REPORT generated by a multi-agent pipeline. "
        "'expected output' is a concise reference summary of the key concepts. "
        "Do NOT penalise the actual output for being longer or more detailed than expected output.",
        "Check only whether the facts in 'actual output' CONTRADICT 'expected output' — contradictions must be penalised.",
        "Check whether the KEY CONCEPTS from 'expected output' are present ANYWHERE in 'actual output', "
        "even if expressed differently, expanded upon, or placed in a different section of the report.",
        "Penalise only when a KEY CONCEPT from 'expected output' is COMPLETELY ABSENT from 'actual output' (not just phrased differently).",
        "Different wording of the same concept is acceptable — do not penalise paraphrasing.",
        "Ignore differences in language (Ukrainian vs English) if the meaning is equivalent.",
    ],
    evaluation_params=[
        LLMTestCaseParams.INPUT,
        LLMTestCaseParams.ACTUAL_OUTPUT,
        LLMTestCaseParams.EXPECTED_OUTPUT,
    ],
    model=EVAL_MODEL,
    threshold=0.45,
)

# ── Pipeline runner ───────────────────────────────────────────────────────────


def _extract_text(content) -> str:
    if isinstance(content, str):
        return content
    if isinstance(content, list):
        return "".join(
            item.get("text", "") if isinstance(item, dict) else str(item)
            for item in content
        )
    return str(content) if content else ""


def _stream_once(payload, config: dict) -> tuple[list, str]:
    """Run one supervisor stream pass; return (interrupts, final_text)."""
    interrupts: list = []
    final_texts: list[str] = []

    for chunk in supervisor.stream(
        payload,
        config=config,
        stream_mode=["updates"],
        version="v2",
    ):
        if chunk["type"] != "updates":
            continue

        data = chunk["data"]

        if "__interrupt__" in data:
            interrupts = list(data["__interrupt__"])
            continue

        model_payload = data.get("model") or {}
        for msg in model_payload.get("messages", []):
            tool_calls = getattr(msg, "tool_calls", []) or []
            if tool_calls:
                if settings.debug:
                    for tc in tool_calls:
                        debug_print(f"  [e2e] supervisor → {tc.get('name', '?')}()")
                continue
            text = _extract_text(getattr(msg, "content", "")).strip()
            if text:
                final_texts.append(text)

        tools_payload = data.get("tools") or {}
        for msg in tools_payload.get("messages", []):
            tool_name = getattr(msg, "name", "tool")
            content = _extract_text(getattr(msg, "content", "")).strip()
            if settings.debug and content:
                debug_print(f"  [e2e] {tool_name} result: {content[:120]}...")

    return interrupts, "\n".join(final_texts).strip()


def run_pipeline(user_input: str) -> str:
    """Run the full pipeline for a user query and return the final report text.

    save_report interrupts are auto-approved so the test runs without human input.
    """
    thread_id = f"e2e-{uuid4().hex[:8]}"
    config = {
        "configurable": {"thread_id": thread_id},
        "recursion_limit": settings.graph_recursion_limit,
    }

    debug_print(f"\n[e2e] Starting pipeline for: {user_input!r}")
    debug_print(f"[e2e] thread_id={thread_id}")

    payload: dict | Command = {"messages": [{"role": "user", "content": user_input}]}
    final_output = ""
    max_rounds = 5  # plan + research + critique + (possible revise) + save

    set_active_thread_id(thread_id)
    try:
        for round_num in range(max_rounds):
            interrupts, text = _stream_once(payload, config)

            if text:
                final_output = text
                debug_print(f"[e2e] round {round_num} text: {text[:120]}...")

            if not interrupts:
                debug_print(f"[e2e] pipeline finished after {round_num + 1} stream round(s).")
                break

            # Extract report content from the save_report interrupt args.
            # IMPORTANT: capture content BEFORE auto-approving and then break —
            # the supervisor's closing message after approval ("The report has been saved…")
            # is meta-commentary, not research, and would overwrite final_output if we
            # continued to the next round. Capturing here and breaking gives the evaluator
            # pure research content instead of wrap-up text.
            report_captured = False
            for interrupt in interrupts:
                int_value = getattr(interrupt, "value", {}) or {}
                for req in int_value.get("action_requests", []):
                    if req.get("name") == "save_report":
                        args = req.get("args") or req.get("arguments") or {}
                        content = args.get("content", "")
                        if isinstance(content, list):
                            content = "".join(
                                item.get("text", "") if isinstance(item, dict) else str(item)
                                for item in content
                            )
                        if content and isinstance(content, str):
                            final_output = content
                            report_captured = True
                            debug_print(f"[e2e] captured report content from interrupt ({len(content)} chars)")

            debug_print(f"[e2e] round {round_num}: interrupt (save_report) → auto-approving")
            payload = Command(resume={"decisions": [{"type": "approve"}]})

            if report_captured:
                # Report content is captured; don't stream another round — the supervisor's
                # post-approval closing message contains only meta-text, not research.
                debug_print("[e2e] report content captured from interrupt, stopping after approval.")
                break

    finally:
        clear_active_thread_id()
        reset_supervisor_limits(thread_id)

    return final_output or "(no output)"


# ── Golden dataset loader ─────────────────────────────────────────────────────


def _load_golden(category: str | None = None) -> list[dict]:
    with DATASET_PATH.open(encoding="utf-8") as f:
        dataset = json.load(f)
    if category:
        dataset = [ex for ex in dataset if ex.get("category") == category]
    return dataset


# ── Tests ─────────────────────────────────────────────────────────────────────


@pytest.mark.parametrize(
    "example",
    _load_golden("happy_path")[:3],
    ids=[f"happy_{i}" for i in range(3)],
)
def test_e2e_happy_path(example: dict) -> None:
    """End-to-end: full pipeline on happy_path examples should produce relevant, correct output."""
    happy_examples = _load_golden("happy_path")
    assert len(happy_examples) >= 3, (
        f"Golden dataset has only {len(happy_examples)} happy_path example(s) — need at least 3. "
        "Add more entries to tests/golden_dataset.json before running this test."
    )
    user_input = example["input"]
    expected_output = example["expected_output"]

    debug_print(f"\n[e2e] test_e2e_happy_path — input: {user_input!r}")

    actual_output = run_pipeline(user_input)

    debug_print(f"[e2e] actual output ({len(actual_output)} chars): {actual_output[:200]}...")

    test_case = LLMTestCase(
        input=user_input,
        actual_output=actual_output,
        expected_output=expected_output,
    )

    deepeval.assert_test(test_case, [answer_relevancy, correctness])


@pytest.mark.parametrize(
    "example",
    _load_golden("failure_case")[:2],
    ids=[f"failure_{i}" for i in range(2)],
)
def test_e2e_failure_cases_graceful(example: dict) -> None:
    """End-to-end: pipeline should not crash and should return a non-empty response for failure cases."""
    user_input = example["input"]

    debug_print(f"\n[e2e] test_e2e_failure_cases — input: {user_input!r}")

    actual_output = run_pipeline(user_input)

    debug_print(f"[e2e] failure case output: {actual_output[:200]}")

    assert actual_output.strip(), (
        f"Pipeline returned empty output for failure case input: {user_input!r}"
    )
    assert len(actual_output) > 20, (
        f"Pipeline output is too short to be a meaningful response: {actual_output!r}"
    )

    # We do not assert correctness here — just answer relevancy to the prompt
    test_case = LLMTestCase(
        input=user_input,
        actual_output=actual_output,
    )
    deepeval.assert_test(test_case, [answer_relevancy])


def test_e2e_full_golden_dataset() -> None:
    """
    Evaluation on the full golden dataset (all 15 examples).

    This is an aggregate evaluation — individual examples can fail; we check the
    overall pass rate stays above a minimum threshold (60% by default).

    Run individually:
      deepeval test run tests/test_e2e.py -k full
    """
    dataset = _load_golden()
    debug_print(f"\n[e2e] Full golden dataset evaluation — {len(dataset)} examples")

    passed = 0
    total = len(dataset)

    for i, example in enumerate(dataset):
        user_input = example["input"]
        expected_output = example["expected_output"]
        category = example.get("category", "unknown")

        debug_print(f"\n[e2e] [{i+1}/{total}] category={category} input={user_input[:80]!r}")

        try:
            actual_output = run_pipeline(user_input)
        except Exception as exc:
            debug_print(f"[e2e] pipeline error: {exc}")
            actual_output = f"(error: {exc})"

        test_case = LLMTestCase(
            input=user_input,
            actual_output=actual_output,
            expected_output=expected_output,
        )

        # Run metrics without asserting — collect pass / fail
        # failure_case: correct refusals score 0 on answer_relevancy, use only correctness
        metrics_for_case = [correctness] if category == "failure_case" else [answer_relevancy, correctness]
        all_passed = True
        for metric in metrics_for_case:
            metric_name = getattr(metric, "name", type(metric).__name__)
            try:
                metric.measure(test_case)
                success = metric.success
                debug_print(
                    f"  {metric_name}: score={metric.score:.3f} "
                    f"({'PASS' if success else 'FAIL'})"
                )
                if not success:
                    all_passed = False
            except Exception as exc:
                all_passed = False
                debug_print(f"  {metric_name}: error — {exc}")

        if all_passed:
            passed += 1
            debug_print(f"  → PASS")
        else:
            debug_print(f"  → FAIL")

    pass_rate = passed / total if total else 0.0
    debug_print(f"\n[e2e] Full dataset result: {passed}/{total} passed ({pass_rate:.0%})")

    min_pass_rate = 0.60
    assert pass_rate >= min_pass_rate, (
        f"Golden dataset pass rate {pass_rate:.0%} is below minimum {min_pass_rate:.0%} "
        f"({passed}/{total} examples passed)."
    )
